server:
  port: 2021
#请求处理的超时时间
ribbon:
  ReadTimeout: 40000
  #请求连接的超时时间
  ConnectTimeout: 1000
spring:
  #  profiles:
  #    include: devConstant
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true
  application:
    name: demo

  #注册中心 配置信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=GMT%2B8
    name: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: config,stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;config.decrypt.key=your public key

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:com.cs.demo.mapper/*.xml
  type-aliases-package: com.cs.demo.eo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


management.endpoints.web.exposure.include: "*"

# 在logs目录下生成spring.log文件
logging:
  path: logs/
  file: logs/app.log
  config: classpath:logback-spring.xml



