package com.cs.demo.eo;

import java.io.Serializable;
import java.util.Date;

public class CourseEo extends CourseEoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_name
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.user_id
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.user_name
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.semester
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private String semester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_times
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private Integer courseTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.stu_count
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private Integer stuCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.visa
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private String visa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.rel_user
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private Long relUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.create_time
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.update_time
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.create_person
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.update_person
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.dr
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private Byte dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.extension
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public CourseEo(Long id, String courseName, Long userId, String userName, String semester, Integer courseTimes, Integer stuCount, String visa, Long relUser, Date createTime, Date updateTime, String createPerson, String updatePerson, Byte dr, String extension) {
        super(id);
        this.courseName = courseName;
        this.userId = userId;
        this.userName = userName;
        this.semester = semester;
        this.courseTimes = courseTimes;
        this.stuCount = stuCount;
        this.visa = visa;
        this.relUser = relUser;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createPerson = createPerson;
        this.updatePerson = updatePerson;
        this.dr = dr;
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public CourseEo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_name
     *
     * @return the value of tb_course.course_name
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_name
     *
     * @param courseName the value for tb_course.course_name
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.user_id
     *
     * @return the value of tb_course.user_id
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.user_id
     *
     * @param userId the value for tb_course.user_id
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.user_name
     *
     * @return the value of tb_course.user_name
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.user_name
     *
     * @param userName the value for tb_course.user_name
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.semester
     *
     * @return the value of tb_course.semester
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public String getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.semester
     *
     * @param semester the value for tb_course.semester
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setSemester(String semester) {
        this.semester = semester == null ? null : semester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_times
     *
     * @return the value of tb_course.course_times
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public Integer getCourseTimes() {
        return courseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_times
     *
     * @param courseTimes the value for tb_course.course_times
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setCourseTimes(Integer courseTimes) {
        this.courseTimes = courseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.stu_count
     *
     * @return the value of tb_course.stu_count
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public Integer getStuCount() {
        return stuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.stu_count
     *
     * @param stuCount the value for tb_course.stu_count
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setStuCount(Integer stuCount) {
        this.stuCount = stuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.visa
     *
     * @return the value of tb_course.visa
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public String getVisa() {
        return visa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.visa
     *
     * @param visa the value for tb_course.visa
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setVisa(String visa) {
        this.visa = visa == null ? null : visa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.rel_user
     *
     * @return the value of tb_course.rel_user
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public Long getRelUser() {
        return relUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.rel_user
     *
     * @param relUser the value for tb_course.rel_user
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setRelUser(Long relUser) {
        this.relUser = relUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.create_time
     *
     * @return the value of tb_course.create_time
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.create_time
     *
     * @param createTime the value for tb_course.create_time
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.update_time
     *
     * @return the value of tb_course.update_time
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.update_time
     *
     * @param updateTime the value for tb_course.update_time
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.create_person
     *
     * @return the value of tb_course.create_person
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.create_person
     *
     * @param createPerson the value for tb_course.create_person
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.update_person
     *
     * @return the value of tb_course.update_person
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.update_person
     *
     * @param updatePerson the value for tb_course.update_person
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.dr
     *
     * @return the value of tb_course.dr
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public Byte getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.dr
     *
     * @param dr the value for tb_course.dr
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setDr(Byte dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.extension
     *
     * @return the value of tb_course.extension
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.extension
     *
     * @param extension the value for tb_course.extension
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CourseEo other = (CourseEo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCourseName() == null ? other.getCourseName() == null : this.getCourseName().equals(other.getCourseName()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getSemester() == null ? other.getSemester() == null : this.getSemester().equals(other.getSemester()))
            && (this.getCourseTimes() == null ? other.getCourseTimes() == null : this.getCourseTimes().equals(other.getCourseTimes()))
            && (this.getStuCount() == null ? other.getStuCount() == null : this.getStuCount().equals(other.getStuCount()))
            && (this.getVisa() == null ? other.getVisa() == null : this.getVisa().equals(other.getVisa()))
            && (this.getRelUser() == null ? other.getRelUser() == null : this.getRelUser().equals(other.getRelUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getExtension() == null ? other.getExtension() == null : this.getExtension().equals(other.getExtension()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCourseName() == null) ? 0 : getCourseName().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getSemester() == null) ? 0 : getSemester().hashCode());
        result = prime * result + ((getCourseTimes() == null) ? 0 : getCourseTimes().hashCode());
        result = prime * result + ((getStuCount() == null) ? 0 : getStuCount().hashCode());
        result = prime * result + ((getVisa() == null) ? 0 : getVisa().hashCode());
        result = prime * result + ((getRelUser() == null) ? 0 : getRelUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getExtension() == null) ? 0 : getExtension().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", courseName=").append(courseName);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", semester=").append(semester);
        sb.append(", courseTimes=").append(courseTimes);
        sb.append(", stuCount=").append(stuCount);
        sb.append(", visa=").append(visa);
        sb.append(", relUser=").append(relUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", dr=").append(dr);
        sb.append(", extension=").append(extension);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}