package com.cs.demo.eo;

import java.io.Serializable;
import java.util.Date;

public class LoginEo extends LoginEoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.user_code
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.token
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.login_flag
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String loginFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.create_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.update_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.create_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.update_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.dr
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Byte dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.extension
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.user_id
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_login
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public LoginEo(Long id, String userCode, String token, String loginFlag, Date createTime, Date updateTime, String createPerson, String updatePerson, Byte dr, String extension, Long userId) {
        super(id);
        this.userCode = userCode;
        this.token = token;
        this.loginFlag = loginFlag;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createPerson = createPerson;
        this.updatePerson = updatePerson;
        this.dr = dr;
        this.extension = extension;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public LoginEo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.user_code
     *
     * @return the value of tb_login.user_code
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.user_code
     *
     * @param userCode the value for tb_login.user_code
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.token
     *
     * @return the value of tb_login.token
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.token
     *
     * @param token the value for tb_login.token
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.login_flag
     *
     * @return the value of tb_login.login_flag
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getLoginFlag() {
        return loginFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.login_flag
     *
     * @param loginFlag the value for tb_login.login_flag
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setLoginFlag(String loginFlag) {
        this.loginFlag = loginFlag == null ? null : loginFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.create_time
     *
     * @return the value of tb_login.create_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.create_time
     *
     * @param createTime the value for tb_login.create_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.update_time
     *
     * @return the value of tb_login.update_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.update_time
     *
     * @param updateTime the value for tb_login.update_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.create_person
     *
     * @return the value of tb_login.create_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.create_person
     *
     * @param createPerson the value for tb_login.create_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.update_person
     *
     * @return the value of tb_login.update_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.update_person
     *
     * @param updatePerson the value for tb_login.update_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.dr
     *
     * @return the value of tb_login.dr
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Byte getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.dr
     *
     * @param dr the value for tb_login.dr
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setDr(Byte dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.extension
     *
     * @return the value of tb_login.extension
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.extension
     *
     * @param extension the value for tb_login.extension
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.user_id
     *
     * @return the value of tb_login.user_id
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.user_id
     *
     * @param userId the value for tb_login.user_id
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LoginEo other = (LoginEo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserCode() == null ? other.getUserCode() == null : this.getUserCode().equals(other.getUserCode()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getLoginFlag() == null ? other.getLoginFlag() == null : this.getLoginFlag().equals(other.getLoginFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getExtension() == null ? other.getExtension() == null : this.getExtension().equals(other.getExtension()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserCode() == null) ? 0 : getUserCode().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getLoginFlag() == null) ? 0 : getLoginFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getExtension() == null) ? 0 : getExtension().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userCode=").append(userCode);
        sb.append(", token=").append(token);
        sb.append(", loginFlag=").append(loginFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", dr=").append(dr);
        sb.append(", extension=").append(extension);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}