package com.cs.demo.eo;

import java.io.Serializable;
import java.util.Date;

public class NoticeEo extends NoticeEoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.title
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.content
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.notice_user
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private Long noticeUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.create_time
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.update_time
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.create_person
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.update_person
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.dr
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private Byte dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.extension
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_notice
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public NoticeEo(Long id, String title, String content, Long noticeUser, Date createTime, Date updateTime, String createPerson, String updatePerson, Byte dr, String extension) {
        super(id);
        this.title = title;
        this.content = content;
        this.noticeUser = noticeUser;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createPerson = createPerson;
        this.updatePerson = updatePerson;
        this.dr = dr;
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public NoticeEo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.title
     *
     * @return the value of tb_notice.title
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.title
     *
     * @param title the value for tb_notice.title
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.content
     *
     * @return the value of tb_notice.content
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.content
     *
     * @param content the value for tb_notice.content
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.notice_user
     *
     * @return the value of tb_notice.notice_user
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public Long getNoticeUser() {
        return noticeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.notice_user
     *
     * @param noticeUser the value for tb_notice.notice_user
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setNoticeUser(Long noticeUser) {
        this.noticeUser = noticeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.create_time
     *
     * @return the value of tb_notice.create_time
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.create_time
     *
     * @param createTime the value for tb_notice.create_time
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.update_time
     *
     * @return the value of tb_notice.update_time
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.update_time
     *
     * @param updateTime the value for tb_notice.update_time
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.create_person
     *
     * @return the value of tb_notice.create_person
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.create_person
     *
     * @param createPerson the value for tb_notice.create_person
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.update_person
     *
     * @return the value of tb_notice.update_person
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.update_person
     *
     * @param updatePerson the value for tb_notice.update_person
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.dr
     *
     * @return the value of tb_notice.dr
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public Byte getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.dr
     *
     * @param dr the value for tb_notice.dr
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setDr(Byte dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.extension
     *
     * @return the value of tb_notice.extension
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.extension
     *
     * @param extension the value for tb_notice.extension
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NoticeEo other = (NoticeEo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getNoticeUser() == null ? other.getNoticeUser() == null : this.getNoticeUser().equals(other.getNoticeUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getExtension() == null ? other.getExtension() == null : this.getExtension().equals(other.getExtension()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getNoticeUser() == null) ? 0 : getNoticeUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getExtension() == null) ? 0 : getExtension().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbg.generated Sat Apr 24 21:54:32 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", noticeUser=").append(noticeUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", dr=").append(dr);
        sb.append(", extension=").append(extension);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}