package com.cs.demo.eo;

import java.io.Serializable;
import java.util.Date;

public class RoleEo extends RoleEoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_code
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_name
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.par_id
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Long parId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.update_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.update_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.dr
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private Byte dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.extension
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public RoleEo(Long id, String roleCode, String roleName, Long parId, Date createTime, Date updateTime, String createPerson, String updatePerson, Byte dr, String extension) {
        super(id);
        this.roleCode = roleCode;
        this.roleName = roleName;
        this.parId = parId;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createPerson = createPerson;
        this.updatePerson = updatePerson;
        this.dr = dr;
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public RoleEo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_code
     *
     * @return the value of tb_role.role_code
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_code
     *
     * @param roleCode the value for tb_role.role_code
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_name
     *
     * @return the value of tb_role.role_name
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_name
     *
     * @param roleName the value for tb_role.role_name
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.par_id
     *
     * @return the value of tb_role.par_id
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Long getParId() {
        return parId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.par_id
     *
     * @param parId the value for tb_role.par_id
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setParId(Long parId) {
        this.parId = parId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_time
     *
     * @return the value of tb_role.create_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_time
     *
     * @param createTime the value for tb_role.create_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.update_time
     *
     * @return the value of tb_role.update_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.update_time
     *
     * @param updateTime the value for tb_role.update_time
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_person
     *
     * @return the value of tb_role.create_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_person
     *
     * @param createPerson the value for tb_role.create_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.update_person
     *
     * @return the value of tb_role.update_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.update_person
     *
     * @param updatePerson the value for tb_role.update_person
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.dr
     *
     * @return the value of tb_role.dr
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public Byte getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.dr
     *
     * @param dr the value for tb_role.dr
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setDr(Byte dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.extension
     *
     * @return the value of tb_role.extension
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.extension
     *
     * @param extension the value for tb_role.extension
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleEo other = (RoleEo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleCode() == null ? other.getRoleCode() == null : this.getRoleCode().equals(other.getRoleCode()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getParId() == null ? other.getParId() == null : this.getParId().equals(other.getParId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getExtension() == null ? other.getExtension() == null : this.getExtension().equals(other.getExtension()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleCode() == null) ? 0 : getRoleCode().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getParId() == null) ? 0 : getParId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getExtension() == null) ? 0 : getExtension().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleCode=").append(roleCode);
        sb.append(", roleName=").append(roleName);
        sb.append(", parId=").append(parId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", dr=").append(dr);
        sb.append(", extension=").append(extension);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}