package com.cs.demo.eo;

import java.io.Serializable;
import java.util.Date;

public class UserEo extends UserEoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_code
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.pwd
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.email
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.role_id
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.role_name
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.rel_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private Long relUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.create_time
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.update_time
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.create_person
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.update_person
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.dr
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private Byte dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.extension
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public UserEo(Long id, String userCode, String pwd, String email, String userName, Long roleId, String roleName, Long relUser, Date createTime, Date updateTime, String createPerson, String updatePerson, Byte dr, String extension) {
        super(id);
        this.userCode = userCode;
        this.pwd = pwd;
        this.email = email;
        this.userName = userName;
        this.roleId = roleId;
        this.roleName = roleName;
        this.relUser = relUser;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createPerson = createPerson;
        this.updatePerson = updatePerson;
        this.dr = dr;
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public UserEo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_code
     *
     * @return the value of tb_user.user_code
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_code
     *
     * @param userCode the value for tb_user.user_code
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.pwd
     *
     * @return the value of tb_user.pwd
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.pwd
     *
     * @param pwd the value for tb_user.pwd
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role_id
     *
     * @return the value of tb_user.role_id
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role_id
     *
     * @param roleId the value for tb_user.role_id
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role_name
     *
     * @return the value of tb_user.role_name
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role_name
     *
     * @param roleName the value for tb_user.role_name
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.rel_user
     *
     * @return the value of tb_user.rel_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public Long getRelUser() {
        return relUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.rel_user
     *
     * @param relUser the value for tb_user.rel_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setRelUser(Long relUser) {
        this.relUser = relUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.create_time
     *
     * @return the value of tb_user.create_time
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.create_time
     *
     * @param createTime the value for tb_user.create_time
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.update_time
     *
     * @return the value of tb_user.update_time
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.update_time
     *
     * @param updateTime the value for tb_user.update_time
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.create_person
     *
     * @return the value of tb_user.create_person
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.create_person
     *
     * @param createPerson the value for tb_user.create_person
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.update_person
     *
     * @return the value of tb_user.update_person
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.update_person
     *
     * @param updatePerson the value for tb_user.update_person
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.dr
     *
     * @return the value of tb_user.dr
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public Byte getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.dr
     *
     * @param dr the value for tb_user.dr
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setDr(Byte dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.extension
     *
     * @return the value of tb_user.extension
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.extension
     *
     * @param extension the value for tb_user.extension
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserEo other = (UserEo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserCode() == null ? other.getUserCode() == null : this.getUserCode().equals(other.getUserCode()))
            && (this.getPwd() == null ? other.getPwd() == null : this.getPwd().equals(other.getPwd()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getRelUser() == null ? other.getRelUser() == null : this.getRelUser().equals(other.getRelUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getExtension() == null ? other.getExtension() == null : this.getExtension().equals(other.getExtension()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserCode() == null) ? 0 : getUserCode().hashCode());
        result = prime * result + ((getPwd() == null) ? 0 : getPwd().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getRelUser() == null) ? 0 : getRelUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getExtension() == null) ? 0 : getExtension().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userCode=").append(userCode);
        sb.append(", pwd=").append(pwd);
        sb.append(", email=").append(email);
        sb.append(", userName=").append(userName);
        sb.append(", roleId=").append(roleId);
        sb.append(", roleName=").append(roleName);
        sb.append(", relUser=").append(relUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", dr=").append(dr);
        sb.append(", extension=").append(extension);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}