package com.cs.demo.mapper;

import com.cs.demo.eo.CourseEo;
import com.cs.demo.eo.CourseEoExample;
import com.cs.demo.eo.CourseEoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseEoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    long countByExample(CourseEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int deleteByExample(CourseEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int deleteByPrimaryKey(CourseEoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int insert(CourseEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int insertSelective(CourseEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    List<CourseEo> selectByExample(CourseEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    CourseEo selectByPrimaryKey(CourseEoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int updateByExampleSelective(@Param("record") CourseEo record, @Param("example") CourseEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int updateByExample(@Param("record") CourseEo record, @Param("example") CourseEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int updateByPrimaryKeySelective(CourseEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Wed Apr 28 18:11:58 CST 2021
     */
    int updateByPrimaryKey(CourseEo record);
}