package com.cs.demo.mapper;

import com.cs.demo.eo.RoleEo;
import com.cs.demo.eo.RoleEoExample;
import com.cs.demo.eo.RoleEoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleEoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    long countByExample(RoleEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int deleteByExample(RoleEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int deleteByPrimaryKey(RoleEoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int insert(RoleEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int insertSelective(RoleEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    List<RoleEo> selectByExample(RoleEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    RoleEo selectByPrimaryKey(RoleEoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int updateByExampleSelective(@Param("record") RoleEo record, @Param("example") RoleEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int updateByExample(@Param("record") RoleEo record, @Param("example") RoleEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int updateByPrimaryKeySelective(RoleEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Apr 20 10:22:58 CST 2021
     */
    int updateByPrimaryKey(RoleEo record);
}