package com.cs.demo.mapper;

import com.cs.demo.eo.UserEo;
import com.cs.demo.eo.UserEoExample;
import com.cs.demo.eo.UserEoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserEoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    long countByExample(UserEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int deleteByExample(UserEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int deleteByPrimaryKey(UserEoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int insert(UserEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int insertSelective(UserEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    List<UserEo> selectByExample(UserEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    UserEo selectByPrimaryKey(UserEoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserEo record, @Param("example") UserEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int updateByExample(@Param("record") UserEo record, @Param("example") UserEoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int updateByPrimaryKeySelective(UserEo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Wed Apr 28 14:49:03 CST 2021
     */
    int updateByPrimaryKey(UserEo record);
}